server:
  port: 8080

spring:
  application:
    name: ai
  
  datasource:
    url: jdbc:postgresql://localhost:5432/ai
    username: ai
    password: ai
    driver-class-name: org.postgresql.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
